/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.foodonthetable.intent;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.proxy.IntentProxy;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import java.lang.StringBuilder;

import java.util.ArrayList;

@Kroll.module(name="Intent", id="com.foodonthetable.intent")
public class IntentModule extends KrollModule {
	// Standard Debugging variables
	private static final String LCAT = "IntentModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	// Constructor
	public IntentModule(final TiContext tiContext) {
		super(tiContext);
	}
	
	// Methods
	@Kroll.method
	public void putIntExtra(final IntentProxy intentProxy, final String key, final Object value) {
		if (DBG) {
			Log.d(LCAT, "putIntExtra called with key:" + key + "\", value:" + value);
		}
		
		if (value instanceof Integer) {
			intentProxy.getIntent().putExtra(key, (Integer) value);
		} else {
			intentProxy.getIntent().putExtra(key, (int) Double.parseDouble(value.toString()));
		}
	}
	
	@Kroll.method
	public String[] getStringArrayListExtra(final IntentProxy intentProxy, final String name) {
		if (DBG) {
			Log.d(LCAT, "getStringArrayListExtra called with name:" + name);
		}
		
		final ArrayList<String> list = intentProxy.getIntent().getStringArrayListExtra(name);
		return list != null ? list.toArray(new String[list.size()]) : null;
	}
}
